Ext.define('Shoppingapp.shoppingapp.shared.com.shoppingapp.model.shoppingcontext.onlineshopping.PaymentDetailsModel.PaymentDetailsModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "amount",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "ccHolderName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "creditCardNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "customerId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "cvvNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "expiryMonth",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "expiryYear",
          "type": "int",
          "defaultValue": ""
     }]
});